### ISSUE TITLE
Missing support for tz column types

### ISSUE THREAD

**Issue by vzsg** [vapor/postgresql#63]
As reported by @hyouuu on Discord, trying to run a query that has a `timestamptz` column, the driver fatal errors with the following output:

```
Thread 1: Fatal error: Error raised at top level: :warning:️ PostgreSQL Error: Could not parse Date from binary data type: UNKNOWN 1184.
- id: PostgreSQLError.date
```

(See also: [numeric constants](https://jdbc.postgresql.org/development/privateapi/constant-values.html). 1184 is the constant for timestamptz.)

---

This is a sneaky issue that eventually hits everyone who used Timestampable with Fluent 2 and has an existing database. That was the case here too: [Fluent 2 and 3 models](https://gist.github.com/hyouuu/8e9e5dc1e3c397d1f72b6abf49b8f514).

In this case, Fluent 2 created columns like this:

![](https://media.discordapp.net/attachments/440601184189808661/446250649403785217/Screen_Shot_2018-05-16_at_3.00.15_AM.png?width=1223&height=656)

**Comment by tanner0101** [comment]
Thanks for the report @vzsg. I will add support for `1184`. 👍

**Comment by broadwaylamb** [comment]
And `timetz` (1266) would be great too.

**Comment by tanner0101** [comment]
`TIMESTAMPTZ` support has been added in #72. I've also added `timetz` to the data types, but there's no way to use it yet. There will need to be a special time type added to make use of it since PSQL will complain if you try to send a full timestamp. Either that or we need to figure out a way to cast it in the query string. 

Feel free to open that as a separate issue. Closing this one 👍
